// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using cw1_api.Models;

#nullable disable

namespace cw1_api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260923135736_First")]
    partial class First
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("cw1_api.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Bolesław Prus",
                            Price = 0m,
                            ReleaseDate = new DateTime(1890, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Lalka"
                        },
                        new
                        {
                            Id = 2,
                            Author = "Fiodor Dostojewski",
                            Price = 0m,
                            ReleaseDate = new DateTime(1866, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Zbrodnia i kara"
                        },
                        new
                        {
                            Id = 3,
                            Author = "Jane Austen",
                            Price = 0m,
                            ReleaseDate = new DateTime(1813, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Duma i uprzedzenie"
                        },
                        new
                        {
                            Id = 4,
                            Author = "J.R.R. Tolkien",
                            Price = 0m,
                            ReleaseDate = new DateTime(1954, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Władca Pierścieni"
                        },
                        new
                        {
                            Id = 5,
                            Author = "Antoine de Saint-Exupéry",
                            Price = 0m,
                            ReleaseDate = new DateTime(1943, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Mały Książę"
                        },
                        new
                        {
                            Id = 6,
                            Author = "George Orwell",
                            Price = 0m,
                            ReleaseDate = new DateTime(1949, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "1984"
                        },
                        new
                        {
                            Id = 7,
                            Author = "Michaił Bułhakow",
                            Price = 0m,
                            ReleaseDate = new DateTime(1967, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Mistrz i Małgorzata"
                        },
                        new
                        {
                            Id = 8,
                            Author = "Gabriel García Márquez",
                            Price = 0m,
                            ReleaseDate = new DateTime(1967, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Sto lat samotności"
                        },
                        new
                        {
                            Id = 9,
                            Author = "J.R.R. Tolkien",
                            Price = 0m,
                            ReleaseDate = new DateTime(1937, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Hobbit"
                        },
                        new
                        {
                            Id = 10,
                            Author = "Andrzej Sapkowski",
                            Price = 0m,
                            ReleaseDate = new DateTime(1993, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Ostatnie życzenie"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
